sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '6.1'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - npm run semantic-release
  - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
