sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6.1'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
  - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
